api_platform:
  mapping:
    paths:
      - '%kernel.project_dir%/src/Entity' # default configuration for annotations

  formats:
    json:
      mime_types: [ 'application/json' ]

  defaults:
    pagination_client_items_per_page: true

  collection:
    pagination:
      items_per_page_parameter_name: perPage
      page_parameter_name: page
